"""NouGenScript: Universal AI Screenplay & Dual-Plane Dramatic Script Engine."""

from nougenscript.core import (
    Cue,
    Dialogue,
    Direction,
    NodeType,
    Scene,
    Screenplay,
    ScriptNode,
)
from nougenscript.dialects import (
    CodeScriptSpec,
    ComicPage,
    ComicPanel,
    CreatorVideoScript,
    EmailSection,
    PolyScript,
    ScriptDomain,
    ScriptKind,
    ScriptMeta,
    TVAct,
    VideoScriptBeat,
)
from nougenscript.dual_plane import DisplaySpan, DualPlaneProjector, SpokenToken
from nougenscript.engine import UniversalScriptEngine
from nougenscript.openclap import ClapDocument, OpenClapSerializer
from nougenscript.parser import FountainParser
from nougenscript.persona import (
    BEHAVIORAL_MASKS,
    EMOTIONS,
    Audience,
    CharacterPersona,
    EmotionState,
    MaskBlend,
    Persona,
    Signals,
    blend,
    get_emotion,
    get_mask,
    list_masks,
    resolve,
)
from nougenscript.narrative_craft import (
    CadenceAnalyzer,
    CadenceMetrics,
    CausalityReport,
    CausalityValidator,
    DramaticIronyMapper,
    InformationState,
    MametAuditResult,
    MametAuditor,
    MasterCraftReport,
    MasterCraftSuite,
    RecurseTracer,
    RecursiveMotif,
    StatusMove,
    StatusTracker,
    StatusTransactionResult,
    StatusTurn,
)
from nougenscript.spite import SpiteProfile, SubtextAnalysisResult, SubtextAnalyzer
from nougenscript.templates import (
    BeatEntry,
    CircleStep,
    EmailTemplate,
    TransitionAnnotation,
    UnityOutline,
    VideoTemplateOutput,
    generate_bab_template,
    generate_beat_sheet,
    generate_hso_template,
    generate_pas_template,
    generate_short_form_reel_template,
    generate_story_circle,
    generate_talking_head_template,
    generate_unity_outline,
    generate_youtube_longform_template,
)
from nougenscript.validators import (
    AristotleUnitiesValidator,
    AwarenessStage,
    BeatSheetValidator,
    BeatType,
    CausalConnector,
    CausalMomentumValidator,
    DeterministicDiffGate,
    HarmonCircleValidator,
    HarmonStep,
    McCloudTransitionValidator,
    PanelTransition,
    SchwartzAwarenessValidator,
    ScriptValidator,
    ValidationIssue,
    ValidationReport,
    VideoRetentionValidator,
)

__version__ = "0.5.0"
__all__ = [
    # Core AST
    "Audience",
    "BEHAVIORAL_MASKS",
    "CadenceAnalyzer",
    "CadenceMetrics",
    "CausalityReport",
    "CausalityValidator",
    "CharacterPersona",
    "ClapDocument",
    "CodeScriptSpec",
    "ComicPage",
    "ComicPanel",
    "CreatorVideoScript",
    "Cue",
    "Dialogue",
    "Direction",
    "DisplaySpan",
    "DramaticIronyMapper",
    "DualPlaneProjector",
    "EMOTIONS",
    "EmailSection",
    "EmotionState",
    "FountainParser",
    "InformationState",
    "MametAuditResult",
    "MametAuditor",
    "MaskBlend",
    "MasterCraftReport",
    "MasterCraftSuite",
    "NodeType",
    "OpenClapSerializer",
    "Persona",
    "PolyScript",
    "RecurseTracer",
    "RecursiveMotif",
    "Scene",
    "Screenplay",
    "ScriptDomain",
    "ScriptKind",
    "ScriptMeta",
    "ScriptNode",
    "Signals",
    "SpiteProfile",
    "SpokenToken",
    "StatusMove",
    "StatusTracker",
    "StatusTransactionResult",
    "StatusTurn",
    "SubtextAnalysisResult",
    "SubtextAnalyzer",
    "TVAct",
    "UniversalScriptEngine",
    "VideoScriptBeat",
    "blend",
    "get_emotion",
    "get_mask",
    "list_masks",
    "resolve",
    # Validators
    "AristotleUnitiesValidator",
    "AwarenessStage",
    "BeatSheetValidator",
    "BeatType",
    "CausalConnector",
    "CausalMomentumValidator",
    "DeterministicDiffGate",
    "HarmonCircleValidator",
    "HarmonStep",
    "McCloudTransitionValidator",
    "PanelTransition",
    "SchwartzAwarenessValidator",
    "ScriptValidator",
    "ValidationIssue",
    "ValidationReport",
    "VideoRetentionValidator",
    # Templates & Scaffolds
    "BeatEntry",
    "CircleStep",
    "EmailTemplate",
    "TransitionAnnotation",
    "UnityOutline",
    "VideoTemplateOutput",
    "generate_bab_template",
    "generate_beat_sheet",
    "generate_hso_template",
    "generate_pas_template",
    "generate_short_form_reel_template",
    "generate_story_circle",
    "generate_talking_head_template",
    "generate_unity_outline",
    "generate_youtube_longform_template",
]
