"""NouGenScript: Universal AI Screenplay & Dual-Plane Dramatic Script Engine."""

from nougenscript.core import (
    Cue,
    Dialogue,
    Direction,
    NodeType,
    Scene,
    Screenplay,
    ScriptNode,
)
from nougenscript.dialects import (
    CodeScriptSpec,
    ComicPage,
    ComicPanel,
    EmailSection,
    PolyScript,
    ScriptDomain,
    ScriptKind,
    ScriptMeta,
    TVAct,
)
from nougenscript.dual_plane import DisplaySpan, DualPlaneProjector, SpokenToken
from nougenscript.engine import UniversalScriptEngine
from nougenscript.openclap import ClapDocument, OpenClapSerializer
from nougenscript.parser import FountainParser
from nougenscript.persona import (
    BEHAVIORAL_MASKS,
    EMOTIONS,
    Audience,
    CharacterPersona,
    EmotionState,
    MaskBlend,
    Persona,
    Signals,
    blend,
    get_emotion,
    get_mask,
    list_masks,
    resolve,
)
from nougenscript.narrative_craft import (
    CadenceAnalyzer,
    CadenceMetrics,
    CausalityReport,
    CausalityValidator,
    DramaticIronyMapper,
    InformationState,
    MametAuditResult,
    MametAuditor,
    MasterCraftReport,
    MasterCraftSuite,
    RecurseTracer,
    RecursiveMotif,
    StatusMove,
    StatusTracker,
    StatusTransactionResult,
    StatusTurn,
)
from nougenscript.spite import SpiteProfile, SubtextAnalysisResult, SubtextAnalyzer

__version__ = "0.4.0"
__all__ = [
    "Audience",
    "BEHAVIORAL_MASKS",
    "CadenceAnalyzer",
    "CadenceMetrics",
    "CausalityReport",
    "CausalityValidator",
    "CharacterPersona",
    "ClapDocument",
    "CodeScriptSpec",
    "ComicPage",
    "ComicPanel",
    "Cue",
    "Dialogue",
    "Direction",
    "DisplaySpan",
    "DramaticIronyMapper",
    "DualPlaneProjector",
    "EMOTIONS",
    "EmailSection",
    "EmotionState",
    "FountainParser",
    "InformationState",
    "MametAuditResult",
    "MametAuditor",
    "MaskBlend",
    "MasterCraftReport",
    "MasterCraftSuite",
    "NodeType",
    "OpenClapSerializer",
    "Persona",
    "PolyScript",
    "RecurseTracer",
    "RecursiveMotif",
    "Scene",
    "Screenplay",
    "ScriptDomain",
    "ScriptKind",
    "ScriptMeta",
    "ScriptNode",
    "Signals",
    "SpiteProfile",
    "SpokenToken",
    "StatusMove",
    "StatusTracker",
    "StatusTransactionResult",
    "StatusTurn",
    "SubtextAnalysisResult",
    "SubtextAnalyzer",
    "TVAct",
    "UniversalScriptEngine",
    "blend",
    "get_emotion",
    "get_mask",
    "list_masks",
    "resolve",
]


